'use client'
import { useTranslations } from 'next-intl'

interface Point { label: string; count: number; total: number }
interface AnalyticsData { totalOrders: number; totalRevenue: number; averageOrder: number; completedOrders: number; daily: Point[]; statuses: Point[]; sources: Point[]; products: Point[]; currency: string }

const statusLabels: Record<string, string> = { new: 'Нове', confirmed: 'Підтверджено', packed: 'Зібрано', shipped: 'Відправлено', done: 'Виконано', cancelled: 'Скасовано' }
const sourceLabels: Record<string, string> = { manual: 'Вручну', website: 'Сайт', woocommerce: 'WooCommerce', phone: 'Телефон', instagram: 'Instagram', facebook: 'Facebook', telegram: 'Telegram' }
const colors = ['bg-blue-500', 'bg-emerald-500', 'bg-violet-500', 'bg-amber-500', 'bg-rose-500', 'bg-cyan-500']

function BarList({ title, points, currency, valueLabel = 'Сума' }: { title: string; points: Point[]; currency: string; valueLabel?: string }) {
  const max = Math.max(...points.map(p => p.total), 1)
  return <section className="rounded-xl border border-gray-200 bg-white p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold text-gray-900">{title}</h2><span className="text-xs text-gray-400">{valueLabel}</span></div><div className="space-y-4">{points.length === 0 ? <p className="text-sm text-gray-400">Даних ще немає.</p> : points.map((p, i) => <div key={p.label}><div className="mb-1 flex justify-between gap-3 text-sm"><span className="truncate font-medium text-gray-700">{p.label}</span><span className="whitespace-nowrap text-gray-500">{p.total.toFixed(2)} {currency} · {p.count}</span></div><div className="h-2 overflow-hidden rounded-full bg-gray-100"><div className={`h-full rounded-full ${colors[i % colors.length]}`} style={{ width: `${Math.max((p.total / max) * 100, 2)}%` }} /></div></div>)}</div></section>
}

export function AnalyticsDashboard({ data }: { data: AnalyticsData }) {
  const t = useTranslations('analyticsNew')
  return <main className="p-4 md:p-6"><div className="mb-6 rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm text-blue-900">{t('salesDescription')}</div><div className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[t('orders'), data.totalOrders.toString(), t('period')], [t('revenue'), `${data.totalRevenue.toFixed(2)} ${data.currency}`, t('orderSum')], [t('averageOrder'), `${data.averageOrder.toFixed(2)} ${data.currency}`, t('revenueDivOrders')], [t('completed'), data.completedOrders.toString(), t('completedHint')]].map(([label, value, hint]) => <div key={label} className="rounded-xl border border-gray-200 bg-white p-5"><div className="text-sm text-gray-500">{label}</div><div className="mt-2 text-2xl font-bold text-gray-900">{value}</div><div className="mt-1 text-xs text-gray-400">{hint}</div></div>)}</div><div className="mb-6 rounded-xl border border-gray-200 bg-white p-5"><div className="mb-5 flex items-center justify-between"><h2 className="font-semibold text-gray-900">{t('salesDynamics')}</h2><span className="text-xs text-gray-400">{t('dayOrdersRevenue')}</span></div><div className="flex h-56 items-end gap-2 overflow-x-auto border-b border-gray-100 pb-1">{data.daily.length === 0 ? <p className="m-auto text-sm text-gray-400">{t('noData')}</p> : data.daily.map((p) => { const max = Math.max(...data.daily.map(x => x.total), 1); return <div key={p.label} className="flex min-w-12 flex-1 flex-col items-center justify-end gap-2" title={`${p.label}: ${p.total.toFixed(2)} ${data.currency}, ${p.count}`}><div className="w-full max-w-10 rounded-t-md bg-blue-500" style={{ height: `${Math.max((p.total / max) * 180, 4)}px` }} /><span className="text-[10px] text-gray-500">{p.label}</span><span className="text-[10px] text-gray-400">{p.count}</span></div> })}</div></div><div className="grid gap-6 lg:grid-cols-3"><BarList title={t('ordersByStatus')} points={data.statuses} currency={data.currency} valueLabel={t('sumCount')} /><BarList title={t('salesSources')} points={data.sources} currency={data.currency} valueLabel={t('sumCount')} /><BarList title={t('topProducts')} points={data.products} currency={data.currency} valueLabel={t('sumCount')} /></div></main>
}
