'use client'
import { useState } from 'react'
import { useTranslations } from 'next-intl'
interface Item { id: string; name: string; sku: string | null; sell_price: number | null }
interface SetRow { id: string; name: string; description: string | null; price: number | null; product_set_items?: Array<{ quantity: number; inventory_items?: { name?: string } | null }> }
export function SetsView({ items, initialSets }: { items: Item[]; initialSets: SetRow[] }) {
  const t = useTranslations('newModules'); const [sets, setSets] = useState(initialSets); const [name, setName] = useState(''); const [price, setPrice] = useState(''); const [selected, setSelected] = useState<Record<string, number>>({}); const [message, setMessage] = useState('')
  async function save(e: React.FormEvent) { e.preventDefault(); setMessage(''); const res = await fetch('/api/product-sets', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, price: price ? Number(price) : null, items: Object.entries(selected).map(([item_id, quantity]) => ({ item_id, quantity })) }) }); const data = await res.json(); if (!res.ok) { setMessage(data.error ?? t('noRecords')); return }; setMessage(t('savedSet')); setName(''); setPrice(''); setSelected({}); window.location.reload() }
  return <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><form onSubmit={save} className="rounded-xl border border-gray-200 bg-white p-5 space-y-4"><h2 className="font-semibold">{t('createSet')}</h2><input required value={name} onChange={e=>setName(e.target.value)} placeholder={t('setName')} className="w-full rounded-lg border border-gray-200 px-3 py-2" /><input type="number" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} placeholder={t('setPrice')} className="w-full rounded-lg border border-gray-200 px-3 py-2" /><div className="max-h-64 space-y-2 overflow-y-auto">{items.map(item => <label key={item.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!selected[item.id]} onChange={e=>setSelected(s=>{ const n={...s}; if(e.target.checked)n[item.id]=1; else delete n[item.id]; return n })} /><span className="flex-1">{item.name}</span>{selected[item.id] && <input type="number" min="1" step="1" value={selected[item.id]} onChange={e=>setSelected(s=>({...s,[item.id]:Number(e.target.value)}))} className="w-16 rounded border px-2 py-1" />}</label>)}</div><button className="rounded-lg bg-blue-600 px-4 py-2 text-sm text-white">{t('saveSet')}</button>{message&&<p className="text-sm text-gray-600">{message}</p>}</form><div className="rounded-xl border border-gray-200 bg-white"><div className="border-b px-5 py-4 font-semibold">{t('sets')}</div>{sets.length===0?<p className="p-6 text-sm text-gray-400">{t('noSets')}</p>:<div className="divide-y">{sets.map(s=><div key={s.id} className="p-4"><div className="font-medium">{s.name}</div><div className="text-sm text-gray-500">{s.product_set_items?.map(i=>`${i.inventory_items?.name ?? t('item')} × ${i.quantity}`).join(', ') || t('noItems')}</div>{s.price!=null&&<div className="mt-1 text-sm font-medium">{s.price}</div>}</div>)}</div>}</div></div>
}
